'use client';

import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Keyboard,
  Search,
  MessageSquare,
  ScanLine,
  Brain,
  BookOpen,
  FileText,
  Timer,
  Globe,
  Library,
  Settings,
  Sun,
  Moon,
  Sparkles,
  Target,
  CalendarDays,
  BarChart3,
  FileSearch,
  Flame,
} from 'lucide-react';
import { useAppStore } from '@/lib/store';

const shortcutGroups = [
  {
    title: 'Navigation',
    shortcuts: [
      { keys: ['Ctrl', 'K'], description: 'Focus web search', icon: Search },
      { keys: ['Ctrl', '/'], description: 'Toggle help dialog', icon: Keyboard },
      { keys: ['?'], description: 'Toggle help dialog', icon: Keyboard },
    ],
  },
  {
    title: 'Tool Switching',
    shortcuts: [
      { keys: ['Ctrl', '1'], description: 'Dashboard', icon: Sparkles },
      { keys: ['Ctrl', '2'], description: 'AI Teacher', icon: MessageSquare },
      { keys: ['Ctrl', '3'], description: 'AI Explainer', icon: Sparkles },
      { keys: ['Ctrl', '4'], description: 'Image Analyzer', icon: ScanLine },
      { keys: ['Ctrl', '5'], description: 'AI Summarizer', icon: FileSearch },
      { keys: ['Ctrl', '6'], description: 'Quiz', icon: Brain },
      { keys: ['Ctrl', '7'], description: 'Flashcards', icon: BookOpen },
      { keys: ['Ctrl', '8'], description: 'Notes', icon: FileText },
      { keys: ['Ctrl', '9'], description: 'Focus Timer', icon: Timer },
      { keys: ['Ctrl', '0'], description: 'Web Research', icon: Globe },
    ],
  },
  {
    title: 'Theme',
    shortcuts: [
      { keys: ['Shift', 'T'], description: 'Toggle light/dark theme', icon: Sun },
    ],
  },
];

const featureTips = [
  {
    title: 'AI Teacher Chat',
    tip: 'Ask questions on any subject. Use voice input (🎤) for hands-free help. Mention a topic to get structured explanations.',
    color: 'text-emerald-500',
    bg: 'bg-emerald-50 dark:bg-emerald-950/30',
  },
  {
    title: 'Image Analyzer',
    tip: 'Upload textbook screenshots, diagrams, or formulas. The AI will explain the content step-by-step.',
    color: 'text-amber-500',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
  },
  {
    title: 'Quiz Generator',
    tip: 'Generate quizzes on any topic. Choose difficulty level and question count. Review wrong answers to learn from mistakes.',
    color: 'text-rose-500',
    bg: 'bg-rose-50 dark:bg-rose-950/30',
  },
  {
    title: 'Flashcards',
    tip: 'Create AI-powered flashcard decks. Use spaced repetition to master concepts faster.',
    color: 'text-violet-500',
    bg: 'bg-violet-50 dark:bg-violet-950/30',
  },
  {
    title: 'Focus Timer',
    tip: 'Use Pomodoro technique: 25 min focus + 5 min break. Track your study sessions over time.',
    color: 'text-orange-500',
    bg: 'bg-orange-50 dark:bg-orange-950/30',
  },
  {
    title: 'Web Research',
    tip: 'Search for academic papers, tutorials, and resources. Perfect for deep dives into topics.',
    color: 'text-teal-500',
    bg: 'bg-teal-50 dark:bg-teal-950/30',
  },
  {
    title: 'Study Goals',
    tip: 'Set daily and weekly study targets. Track progress with visual indicators and stay motivated!',
    color: 'text-emerald-500',
    bg: 'bg-emerald-50 dark:bg-emerald-950/30',
  },
  {
    title: 'AI Study Plan',
    tip: 'Get a personalized study plan generated by AI. Includes daily tasks, resources, milestones and export to Markdown.',
    color: 'text-teal-500',
    bg: 'bg-teal-50 dark:bg-teal-950/30',
  },
  {
    title: 'AI Summarizer',
    tip: 'Paste any lecture notes or articles and get AI-powered summaries in 4 styles: Brief, Detailed, Bullet Points, or ELI5.',
    color: 'text-cyan-500',
    bg: 'bg-cyan-50 dark:bg-cyan-950/30',
  },
  {
    title: 'Study Streak',
    tip: 'Track your daily study streak with a visual heatmap. Stay motivated by building consecutive study days!',
    color: 'text-amber-500',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
  },
  {
    title: 'Statistics',
    tip: 'View your study analytics: total hours, quiz performance, flashcard mastery, and export reports.',
    color: 'text-cyan-500',
    bg: 'bg-cyan-50 dark:bg-cyan-950/30',
  },
  {
    title: 'Mood Tracker',
    tip: 'Log how you feel about your studies each day. Track your mood trends to find patterns in your learning efficiency.',
    color: 'text-rose-500',
    bg: 'bg-rose-50 dark:bg-rose-950/30',
  },
  {
    title: 'AI Solver',
    tip: 'Get step-by-step solutions for math problems, code challenges, and general questions. Includes copy, TTS, and history.',
    color: 'text-violet-500',
    bg: 'bg-violet-50 dark:bg-violet-950/30',
  },
  {
    title: 'Achievements',
    tip: 'Unlock badges by completing learning milestones. Track your progress across 14 different challenges.',
    color: 'text-amber-500',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
  },
];

function Kbd({ children }: { children: React.ReactNode }) {
  return (
    <kbd className="inline-flex items-center justify-center min-w-[1.75rem] h-6 px-1.5 rounded-md border border-border bg-muted font-mono text-[11px] font-medium text-foreground shadow-sm">
      {children}
    </kbd>
  );
}

export function HelpDialog() {
  const { showHelp, setShowHelp } = useAppStore();

  return (
    <Dialog open={showHelp} onOpenChange={setShowHelp}>
      <DialogContent className="sm:max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <div className="w-8 h-8 rounded-lg bg-emerald-100 dark:bg-emerald-900/40 flex items-center justify-center">
              <Keyboard className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
            </div>
            Keyboard Shortcuts & Help
          </DialogTitle>
          <DialogDescription>
            Master Ilmexa AI with these keyboard shortcuts and feature tips.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5 mt-2">
          {/* Shortcut Groups */}
          {shortcutGroups.map((group) => (
            <div key={group.title}>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2.5">
                {group.title}
              </h3>
              <div className="grid gap-1.5">
                {group.shortcuts.map((shortcut) => (
                  <div
                    key={shortcut.description}
                    className="flex items-center justify-between rounded-lg px-3 py-2 hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-2.5">
                      <shortcut.icon className="w-4 h-4 text-muted-foreground" />
                      <span className="text-sm">{shortcut.description}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      {shortcut.keys.map((key, i) => (
                        <React.Fragment key={key}>
                          {i > 0 && <span className="text-muted-foreground text-xs">+</span>}
                          <Kbd>{key}</Kbd>
                        </React.Fragment>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}

          {/* Divider */}
          <div className="border-t" />

          {/* Feature Tips */}
          <div>
            <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2.5">
              Feature Tips
            </h3>
            <div className="grid gap-2">
              {featureTips.map((tip) => (
                <Card key={tip.title} className="border shadow-none">
                  <CardContent className={`p-3 rounded-lg ${tip.bg}`}>
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`text-sm font-semibold ${tip.color}`}>{tip.title}</span>
                    </div>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      {tip.tip}
                    </p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* Bottom tip */}
          <div className="flex items-center justify-center gap-2 pt-2">
            <Badge variant="secondary" className="text-xs font-normal">
              💡 Press <Kbd className="ml-1 text-[10px]">?</Kbd> anytime to open this dialog
            </Badge>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
